### PR TITLE
Fix redmine importer fetching redundant issues

### PR DESCRIPTION
**Pull request by djdupre**
The importer was fetching each issue individually even though they were already fetched 100 at a time.

With this I was able to import the TestCreditSystem project which has over 20,000 issues. No need to use a different CORS server.

### CODE REVIEW

**Comment by cjteam123** [comment]
Looks like the coverage needs some work. You can override if you want.

**Comment by cjteam123** [comment]
Fixes #161

**Comment by cjteam123** [comment]
Ah, that was a good move. Do you have any idea what the field was for?

**Comment by djdupre** [comment]
The project ID is required when fetching issues, but it's also included in the project response. I just waited for the project to come in before getting issues.

**Pull request merged**
