### PR TITLE
[Add] json input

### LINKED ISSUE #32: Add importing for JSON

### PR DESCRIPTION
**Pull request by cjteam123**
Fixes #32

### CODE REVIEW

**Comment by cjteam123** [comment]
@djdupre Any idea what's causing the ci tests to fail? It seems to be claiming that the googlecode component doesn't exist??

**Comment by djdupre** [comment]
Your component tests must import FormsModule.

**Comment by cjteam123** [comment]
@djdupre I've added the import, but there still seems to be something wrong. I'm probably missing something somewhere...

**Comment by djdupre** [comment]
We should [stub the nested components](https://angular.io/guide/testing#stubbing-unneeded-components) for ImportPageComponent, like we're already doing with ImportGithubStubComponent.

**Pull request merged**
